# Site settings
title: Trevor D.
description: 'Email: Trevor@thefogameproject.dev ' 
url: 'https://thefogameproject.dev'
baseurl: ''
font_awesome: '57918ba98d.js'


author:
  name: 'Trevor D.'

# The order of the social links is defined by their order in this list
socials:
  github:
    user_id: fogame234
  linkedin:
    user_id: trevordavis_cyber

  

defaults:
  -
    scope:
      path: ''
      type: 'pages'
    values:
        layout: 'default'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png', 'docker-compose.yml', 'socials/', 'node_modules', 'vendor/bundle/', 'vendor/cache/', 'vendor/gems/', 'vendor/ruby/']
