# Jekyll configuration

name: Fogame's Blog
title: Fogame's Blog
description: Software Developer


#url: http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organization's page leave it empty)
baseurl: '/ctf'

author: Fogame
copyright: 2024-2025

permalink: /:year/:month/:title/

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
